// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your apii key',
    appId: '1:613995925532:web:7fa5b2cf361fde6b340fd9',
    messagingSenderId: '613995925532',
    projectId: 'prescripto-b77f2',
    authDomain: 'prescripto-b77f2.firebaseapp.com',
    storageBucket: 'prescripto-b77f2.appspot.com',
    measurementId: 'G-JCRDJ4ET1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUsv4s-S-MEmGvgtkKztjVsmIotdKL7K0',
    appId: '1:613995925532:android:dc6214eff58e0b00340fd9',
    messagingSenderId: '613995925532',
    projectId: 'prescripto-b77f2',
    storageBucket: 'prescripto-b77f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRKxtyfK78POxOJo9m2iDr9RaG2QcN9XM',
    appId: '1:613995925532:ios:bd0ab1ab8a234c1b340fd9',
    messagingSenderId: '613995925532',
    projectId: 'prescripto-b77f2',
    storageBucket: 'prescripto-b77f2.appspot.com',
    iosBundleId: 'com.example.prescripto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRKxtyfK78POxOJo9m2iDr9RaG2QcN9XM',
    appId: '1:613995925532:ios:bd0ab1ab8a234c1b340fd9',
    messagingSenderId: '613995925532',
    projectId: 'prescripto-b77f2',
    storageBucket: 'prescripto-b77f2.appspot.com',
    iosBundleId: 'com.example.prescripto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOhq3A7zr1NTdJcZWZ5vzjceIDK7BPohk',
    appId: '1:613995925532:web:9bf07247d4d76d18340fd9',
    messagingSenderId: '613995925532',
    projectId: 'prescripto-b77f2',
    authDomain: 'prescripto-b77f2.firebaseapp.com',
    storageBucket: 'prescripto-b77f2.appspot.com',
    measurementId: 'G-QQQXKKP91Q',
  );
}
